const products = [
  {
    _id: "1",
    name: "Mc cringe",
    image: "/images/cring.webp",
    description:
      "Introducing the MC cringe Tee. The artist was originally inspired by Jackson Pollock in terms of splashes and brushwork. The colors provide a commentary on the MC crringe gangs of Mumbai and realizes their impact on the genre of meme lifestyle. This streetwear cut tee, with sublimation printing on the fabric, is hyper-comfortable and as a result, the perfect wardrobe choice for the summers. Fabric: 80% Cotton – 20% Polyester",
    brand: "Puneet",
    category: "Clothing",
    price: 100.99,
    countInStock: 5,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "2",
    name: "Sabka Baap ek",
    image: "/images/baap.png",
    description:
      "Introducing the Sabka baap ek T-Shirt, perfect for those who love high-end streetwear with a touch of luxury. This T-shirt is made from 100% cotton and It's perfect for everyday wear or for making a statement at your next big event. The screen printing and embroidery on the front add a touch of luxury, while the logo with colors gives it an exclusive look that will make you stand out from the crowd.",
    brand: "Puneet",
    category: "Clothing",
    price: 150.99,
    countInStock: 5,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "3",
    name: "Lords Supremacy",
    image: "/images/supremacy.png",
    description:
      "Our Lords Supremacy tee is the perfect way to show your streetwear style. With its sublimation printing on fabric, it's guaranteed to turn heads. Made from 80% cotton and 20% polyester, it's both comfortable and stylish. And because it's inspired by the meme gang, you know it's tough enough to handle anything. Colors has never looked better",
    brand: "Puneet",
    category: "Clothing",
    price: 150.99,
    countInStock: 5,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "4",
    name: "Super Star",
    image: "/images/lord.png",
    description:
      "The Super Star tee celebrates the iconic design aesthetics that we have all come to love. These colorful Cuban collar shirts from lords are sure to become your summer go-to. It’s crafted in Mumbai using linen fabric, so it’s comfy, moisture-wicking, and breathable. Wrapped in vibrant, unique print these shirts feature a camp collar for an effortlessly cool touch, pair it with a white tee for a relaxed weekend look.",
    brand: "Puneet",
    category: "Clothing",
    price: 150.99,
    countInStock: 5,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Yeah",
    image: "/images/Yeah.webp",
    description:
      "Continuing our journey in the Rustic World of this water-paint-influenced abstract. The artist further explores the earthy tones in the shades of dark sage and coral. These colorful Cuban collar shirts from Lord are sure to become your summer go-to. It’s crafted in mumbai using linen fabric, so it’s comfy, moisture-wicking, and breathable. All of our products of this specific line are printed using digital printing technology with great attention to detail to ensure the long lasting vividness of colors and crisp print wash after wash.",
    brand: "Puneet",
    category: "Clothing",
    price: 100.99,
    countInStock: 5,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "BDSM",
    image: "/images/BDSM.webp",
    description:
      "FABRIC - 100% Cotton, 180 GSM, Double Bio-Washed COLOUR - Black PRINTING - DTF Printed STYLE - Standard Fit, Round Neck, Short Sleeves SIZE - Please refer to the size chart COUNTRY OF ORIGIN - India",
    brand: "Puneet",
    category: "Clothing",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "7",
    name: "Founders look ",
    image: "/images/founders.webp",
    description:
      "The Founder Lokk tee celebrates the iconic design aesthetics that we have all come to love. These colorful Cuban collar shirts from lords are sure to become your summer go-to. It’s crafted in Mumbai using linen fabric, so it’s comfy, moisture-wicking, and breathable. Wrapped in vibrant, unique print these shirts feature a camp collar for an effortlessly cool touch, pair it with a white tee for a relaxed weekend look.",
    brand: "Puneet",
    category: "Clothing",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "Vision Creativity Passion",
    image: "/images/i_eat_ass.webp",
    description:
      "Vision Creativity Passion T-Shirt celebrates the iconic design aesthetics that we have all come to love. These colorful Cuban collar shirts from lords are sure to become your summer go-to. It’s crafted in Mumbai using linen fabric, so it’s comfy, moisture-wicking, and breathable. Wrapped in vibrant, unique print these shirts feature a camp collar for an effortlessly cool touch, pair it with a white tee for a relaxed weekend look.",
    brand: "Puneet",
    category: "Clothing",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "9",
    name: "Pain Hub",
    image: "/images/pain_hub.webp",
    description:
      "Introducing the Pain Hub Tee. The artist was originally inspired by Jackson Pollock in terms of splashes and brushwork. The colors provide a commentary on the Pain hub gangs of Mumbai and realizes their impact on the genre of meme lifestyle. This streetwear cut tee, with sublimation printing on the fabric, is hyper-comfortable and as a result, the perfect wardrobe choice for the summers. Fabric: 80% Cotton – 20% Polyester",
    brand: "Puneet",
    category: "Clothing",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "10",
    name: "MC Stan",
    image: "/images/mc_stan.webp",
    description:
      "Introducing the MC Stan Tee. The artist was originally inspired by Jackson Pollock in terms of splashes and brushwork. The colors provide a commentary on the Stan gangs of Mumbai and realizes their impact on the genre of meme lifestyle. This streetwear cut tee, with sublimation printing on the fabric, is hyper-comfortable and as a result, the perfect wardrobe choice for the summers. Fabric: 80% Cotton – 20% Polyester",
    brand: "Puneet",
    category: "Clothing",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "11",
    name: "Tera Ghar Jayenga",
    image: "/images/tera_ghar_jayenga.webp",
    description:
      "Introducing the Tera Ghar Jayenga Tee. The artist was originally inspired by Jackson Pollock in terms of splashes and brushwork. The colors provide a commentary on the Ghar gangs of Mumbai and realizes their impact on the genre of meme lifestyle. This streetwear cut tee, with sublimation printing on the fabric, is hyper-comfortable and as a result, the perfect wardrobe choice for the summers. Fabric: 80% Cotton – 20% Polyester",
    brand: "Puneet",
    category: "Clothing",
    price: 69.99,
    countInStock: 10,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "12",
    name: "Women",
    image: "/images/women.webp",
    description:
      "Introducing the Women Tee. The artist was originally inspired by Jackson Pollock in terms of splashes and brushwork. The colors provide a commentary on the meme gangs of Mumbai and realizes their impact on the genre of meme lifestyle. This streetwear cut tee, with sublimation printing on the fabric, is hyper-comfortable and as a result, the perfect wardrobe choice for the summers. Fabric: 80% Cotton – 20% Polyester",
    brand: "Puneet",
    category: "Clothing",
    price: 55.99,
    countInStock: 7,
    rating: 4,
    numReviews: 7,
  },
];

export default products;
